### ISSUE TITLE
Expand the guide more

### ISSUE THREAD

**Issue by SnowSquire** [dominik-korsa/discord-integration#5]
I followed the guide and I can get Minecraft messages in discord but discord messages don't go in mc chat and death messages dont go into discord chat. Join messages also don't appear. I cant figure what I need to change from the default config to get it to work

**Comment by dominik-korsa** [comment]
Up to v2.1.0 Minecraft chat messages were sent to Discord using the webhook but status (join, quit and death) messages were sent using the Discord bot. Since v2.2.0 (released today) status messages are also sent via the webhook - so first update the plugin.

Other than the webhook, you also need to configure the Discord bot.
First, make sure you've invited the bot as [explained here](https://github.com/dominik-korsa/discord-integration/wiki/Configuring-a-Discord-bot#inviting-the-bot-to-your-server). If you did, you should be able to see it in your Discord server's member list.
If the `discord-token` is valid you should see a `Discord Integration connected` message in the console after starting the server or using `/di reload`. The Discord Bot should become active. I've named my `Dominik Korsa's test bot`, so I see this in my Discord server member list:
![image](https://user-images.githubusercontent.com/29484605/147505270-56cea43f-a187-4e54-a0ca-ae22b48bb368.png)
Last, make sure you've added the channel ID you want to sync in the `config.yaml`, like this:
```yaml
chat:
  channels:
    - 123456789123456789
```

Please let me know if you managed to get it working

**Comment by SnowSquire** [comment]
It worked thank you very much. I did have the bot in my server by the way.

**Comment by SnowSquire** [comment]
Also you should sync advancements to the discord channel as well

**Comment by dominik-korsa** [comment]
I've already tried syncing advancements but it's way harder than it appears. Basically, the server doesn't have the image and language assets of advancements, only their IDs. It's still on my TODO list though 🙂
